# OP-Node values for localnet

replicaCount: 1

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

persistence:
  enabled: false

nodeSelector: {}

tolerations: []

config:
  network: "localnet"
  l1ChainId: 1337
  l2ChainId: 1337
  l1:
    rpcUrl: "http://l1-geth:8545"
    rpcKind: "basic"
  p2p:
    bootnodes: []


