# OP-Node values for mainnet

replicaCount: 3

resources:
  limits:
    cpu: 4000m
    memory: 8Gi
  requests:
    cpu: 2000m
    memory: 4Gi

persistence:
  enabled: true
  size: 100Gi

nodeSelector:
  role: core

tolerations:
  - key: workload
    operator: Equal
    value: core
    effect: NoSchedule

config:
  network: "mainnet"
  l1ChainId: 8453
  l2ChainId: 8888
  l1:
    rpcUrl: "https://mainnet.base.org"
    rpcKind: "alchemy"
  p2p:
    bootnodes: []

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - op-node
        topologyKey: kubernetes.io/hostname


