replicaCount: 1

image:
  repository: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-challenger
  pullPolicy: IfNotPresent
  tag: "v1.7.6"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "7300"

podSecurityContext:
  fsGroup: 1000
  runAsUser: 1000
  runAsNonRoot: true

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  metrics:
    port: 7300

resources:
  limits:
    cpu: 2000m
    memory: 4Gi
  requests:
    cpu: 1000m
    memory: 2Gi

persistence:
  enabled: true
  storageClass: "gp3"
  accessMode: ReadWriteOnce
  size: 50Gi
  mountPath: /data

nodeSelector:
  role: core

tolerations:
  - key: workload
    operator: Equal
    value: core
    effect: NoSchedule

affinity: {}

config:
  l1:
    rpcUrl: ""
  rollup:
    rpcUrl: "http://op-node:9545"
  l2:
    rpcUrl: "http://reth-sequencer:8545"
  traceType: "cannon"  # or "asterisc"
  gameFactoryAddress: ""
  gameAllowlist: []
  datadir: "/data"
  maxConcurrency: 10
  pollInterval: "12s"
  privateKey: ""  # Should be injected from Vault
  metrics:
    enabled: true
    addr: "0.0.0.0"
    port: 7300
  pprof:
    enabled: false


