# OP-Challenger values for localnet (disabled)

replicaCount: 0

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

persistence:
  enabled: false

nodeSelector: {}

tolerations: []

config:
  l1:
    rpcUrl: "http://l1-geth:8545"



