name: Predimarket Tests

on:
  push:
    branches: [main, develop]
    paths:
      - 'apps/predimarket/**'
  pull_request:
    branches: [main, develop]
    paths:
      - 'apps/predimarket/**'

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/predimarket
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: bun install
      
      - name: Run unit tests
        run: bun run test:unit
      
      - name: Type checking
        run: bun run lint

  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/predimarket
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: bun install
      
      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium
      
      - name: Run E2E tests
        run: bun run test:e2e
        env:
          CI: true
      
      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: apps/predimarket/playwright-report/
          retention-days: 7

  build:
    name: Build Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/predimarket
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: bun install
      
      - name: Build production
        run: bun run build
      
      - name: Check bundle size
        run: |
          echo "Bundle sizes:"
          ls -lh .next/static/chunks/ | head -10

