replicaCount: 1

image:
  repository: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-batcher
  pullPolicy: IfNotPresent
  tag: "v1.7.6"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "7300"

podSecurityContext:
  fsGroup: 1000
  runAsUser: 1000
  runAsNonRoot: true

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  rpc:
    port: 8545
  metrics:
    port: 7300

resources:
  limits:
    cpu: 2000m
    memory: 4Gi
  requests:
    cpu: 1000m
    memory: 2Gi

nodeSelector:
  role: core

tolerations:
  - key: workload
    operator: Equal
    value: core
    effect: NoSchedule

affinity: {}

config:
  l1:
    rpcUrl: ""
  l2:
    rpcUrl: "http://reth-sequencer:8545"
  rollup:
    rpcUrl: "http://op-node:9545"
  maxChannelDuration: 1
  subSafetyMargin: 4
  pollInterval: "6s"
  numConfirmations: 1
  safeAbortNonceTooLowCount: 3
  resubmission: "12s"
  batchType: 1
  dataAvailability:
    type: "eigenda"  # or "blobs" or "calldata"
  privateKey: ""  # Should be injected from Vault
  sequencerHd: ""
  metrics:
    enabled: true
    addr: "0.0.0.0"
    port: 7300
  pprof:
    enabled: false


