# OP-Batcher values for localnet

replicaCount: 1

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

nodeSelector: {}

tolerations: []

config:
  l1:
    rpcUrl: "http://l1-geth:8545"
  dataAvailability:
    type: "calldata"



