# Helmfile for deploying Jeju infrastructure across environments
# Usage: helmfile -e <environment> sync

# Available environments: localnet, testnet, mainnet
environments:
  localnet:
    values:
      - environments/localnet.yaml
  testnet:
    values:
      - environments/testnet.yaml
  mainnet:
    values:
      - environments/mainnet.yaml

---

repositories:
  - name: jetstack
    url: https://charts.jetstack.io
  - name: aws
    url: https://aws.github.io/eks-charts

---

releases:
  # AWS Load Balancer Controller (required for ingress)
  - name: aws-load-balancer-controller
    namespace: kube-system
    chart: aws/aws-load-balancer-controller
    version: 1.7.0
    installed: {{ ne .Environment.Name "localnet" }}
    set:
      - name: clusterName
        value: jeju-{{ .Environment.Name }}
      - name: serviceAccount.create
        value: "false"
      - name: serviceAccount.name
        value: aws-load-balancer-controller
      - name: enableWaf
        value: "true"
      - name: enableWafv2
        value: "true"
      - name: enableShield
        value: {{ eq .Environment.Name "mainnet" | quote }}

  # Cert-Manager for SSL certificates
  - name: cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: jetstack/cert-manager
    version: v1.13.0
    installed: {{ ne .Environment.Name "localnet" }}
    values:
      - installCRDs: true
      - ../helm/cert-manager/values-{{ .Environment.Name }}.yaml

  # OP-Node (Consensus Layer)
  - name: op-node
    namespace: op-stack
    createNamespace: true
    chart: ../helm/op-node
    values:
      - ../helm/op-node/values.yaml
      - ../helm/op-node/values-{{ .Environment.Name }}.yaml

  # Reth Sequencer (Execution Layer - Sequencer)
  - name: reth-sequencer
    namespace: execution
    createNamespace: true
    chart: ../helm/reth
    values:
      - ../helm/reth/values.yaml
      - mode: "sequencer"

  # Reth RPC (Execution Layer - RPC Nodes)
  - name: reth-rpc
    namespace: rpc
    createNamespace: true
    chart: ../helm/reth
    values:
      - ../helm/reth/values.yaml
      - ../helm/reth/values-rpc-{{ .Environment.Name }}.yaml
      - mode: "rpc"

  # Reth Archive (Execution Layer - Archive Node)
  - name: reth-archive
    namespace: rpc
    chart: ../helm/reth
    values:
      - ../helm/reth/values.yaml
      - ../helm/reth/values-archive-{{ .Environment.Name }}.yaml
      - mode: "archive"

  # OP-Batcher (Transaction Batcher)
  - name: op-batcher
    namespace: op-stack
    chart: ../helm/op-batcher
    values:
      - ../helm/op-batcher/values.yaml
      - ../helm/op-batcher/values-{{ .Environment.Name }}.yaml

  # OP-Proposer (State Root Proposer)
  - name: op-proposer
    namespace: op-stack
    chart: ../helm/op-proposer
    values:
      - ../helm/op-proposer/values.yaml
      - ../helm/op-proposer/values-{{ .Environment.Name }}.yaml

  # OP-Challenger (Fault Proof Challenger)
  - name: op-challenger
    namespace: op-stack
    chart: ../helm/op-challenger
    installed: {{ ne .Environment.Name "localnet" }}
    values:
      - ../helm/op-challenger/values.yaml
      - ../helm/op-challenger/values-{{ .Environment.Name }}.yaml

  # EigenDA Proxy (Data Availability)
  - name: eigenda
    namespace: da
    createNamespace: true
    chart: ../helm/eigenda
    values:
      - ../helm/eigenda/values.yaml
      - ../helm/eigenda/values-{{ .Environment.Name }}.yaml

  # ERC-4337 Bundler (Account Abstraction)
  - name: bundler
    namespace: aa
    createNamespace: true
    chart: ../helm/bundler
    installed: {{ ne .Environment.Name "localnet" }}
    values:
      - ../helm/bundler/values.yaml
      - ../helm/bundler/values-{{ .Environment.Name }}.yaml

  # RPC Gateway (Load Balancer + Rate Limiting)
  - name: rpc-gateway
    namespace: rpc
    chart: ../helm/rpc-gateway
    values:
      - ../helm/rpc-gateway/values.yaml
      - ../helm/rpc-gateway/values-{{ .Environment.Name }}.yaml

  # Subsquid Indexer (Blockchain Data Indexer)
  - name: subsquid
    namespace: indexer
    createNamespace: true
    chart: ../helm/subsquid
    installed: {{ ne .Environment.Name "localnet" }}
    values:
      - ../helm/subsquid/values.yaml
      - ../helm/subsquid/values-{{ .Environment.Name }}.yaml

