name = "github-auth-worker"
main = "dist/index.js"
compatibility_date = "2023-10-30"

[build]
command = "bun run build"

[vars]
ALLOWED_ORIGIN = "https://jejunetwork.github.io"
# Secrets (to be set via `npx wrangler secret put <NAME>`) in production:
# GITHUB_CLIENT_ID
# GITHUB_CLIENT_SECRET 

[env.dev.vars]
ALLOWED_ORIGIN = "http://localhost:3000"
