apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "subsquid.fullname" . }}-processor
  labels:
    {{- include "subsquid.labels" . | nindent 4 }}
    component: processor
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "subsquid.selectorLabels" . | nindent 6 }}
      component: processor
  template:
    metadata:
      labels:
        {{- include "subsquid.selectorLabels" . | nindent 8 }}
        component: processor
    spec:
      serviceAccountName: {{ include "subsquid.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: processor
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.processor.image.repository }}:{{ .Values.processor.image.tag }}"
          imagePullPolicy: {{ .Values.processor.image.pullPolicy }}
          command: ["node", "lib/processor.js"]
          env:
            {{- toYaml .Values.processor.env | nindent 12 }}
          resources:
            {{- toYaml .Values.processor.resources | nindent 12 }}
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "ps aux | grep 'node lib/processor.js' | grep -v grep"
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}

