apiVersion: v1
kind: Service
metadata:
  name: {{ include "subsquid.fullname" . }}-api
  labels:
    {{- include "subsquid.labels" . | nindent 4 }}
    component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "subsquid.selectorLabels" . | nindent 4 }}
    component: api

