{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "subsquid.fullname" . }}-postgres
  labels:
    {{- include "subsquid.labels" . | nindent 4 }}
    component: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "subsquid.selectorLabels" . | nindent 4 }}
    component: postgres
{{- end }}

