version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: jeju-explorer-api
    restart: unless-stopped
    ports:
      - "4002:4002"
    environment:
      - PORT=4002
    volumes:
      - ./node-explorer.db:/app/node-explorer.db
    networks:
      - jeju-explorer

  collector:
    build:
      context: .
      dockerfile: Dockerfile.collector
    container_name: jeju-explorer-collector
    restart: unless-stopped
    environment:
      - API_URL=http://api:4002
      - COLLECTOR_PRIVATE_KEY=${COLLECTOR_PRIVATE_KEY}
      - SCAN_INTERVAL=300000
    depends_on:
      - api
    networks:
      - jeju-explorer

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jeju-explorer-frontend
    restart: unless-stopped
    ports:
      - "3011:3011"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4002
    depends_on:
      - api
    networks:
      - jeju-explorer

networks:
  jeju-explorer:
    name: jeju-explorer

