/**
 * @fileoverview Bootstrap Autocrat for localnet development
 *
 * This script:
 * 1. Deploys all required contracts
 * 2. Initializes pools and markets
 * 3. Funds the bot wallet
 * 4. Starts the autocrat service
 *
 * Usage:
 *   bun run scripts/bootstrap.ts
 */

import {
  createPublicClient,
  createWalletClient,
  http,
  parseEther,
  formatEther,
} from 'viem';
import { privateKeyToAccount } from 'viem/accounts';
import { execSync } from 'child_process';
import { join } from 'path';

// ============ Configuration ============

const RPC_URL = process.env.LOCALNET_RPC_URL || 'http://localhost:8545';
const CONTRACTS_DIR = join(__dirname, '../../../packages/contracts');

// Anvil's default private keys
const DEPLOYER_KEY = '0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80';
const BOT_KEY = process.env.AUTOCRAT_PRIVATE_KEY || '0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d';

// ============ Main ============

async function main() {
  console.log('\n╔════════════════════════════════════════╗');
  console.log('║     AUTOCRAT LOCALNET BOOTSTRAP        ║');
  console.log('╚════════════════════════════════════════╝\n');

  const chain = {
    id: 1337,
    name: 'Localnet',
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    rpcUrls: { default: { http: [RPC_URL] } },
  };

  const deployer = privateKeyToAccount(DEPLOYER_KEY as `0x${string}`);
  const botAccount = privateKeyToAccount(BOT_KEY as `0x${string}`);

  const publicClient = createPublicClient({
    chain,
    transport: http(RPC_URL),
  });

  const walletClient = createWalletClient({
    account: deployer,
    chain,
    transport: http(RPC_URL),
  });

  console.log('📍 Configuration:');
  console.log(`   RPC URL: ${RPC_URL}`);
  console.log(`   Deployer: ${deployer.address}`);
  console.log(`   Bot Wallet: ${botAccount.address}`);

  // Check connection
  try {
    const blockNumber = await publicClient.getBlockNumber();
    console.log(`   Block: ${blockNumber}`);
  } catch {
    console.error('\n❌ Cannot connect to RPC. Is anvil running?');
    console.log('   Start with: anvil\n');
    process.exit(1);
  }

  // 1. Deploy contracts
  console.log('\n📦 Deploying contracts...');

  try {
    // Set dummy API keys for localnet (not needed but foundry.toml references them)
    const output = execSync(
      `cd ${CONTRACTS_DIR} && BASESCAN_API_KEY=dummy ETHERSCAN_API_KEY=dummy forge script script/DeployAutocrat.s.sol:DeployAutocratLocalnet --rpc-url ${RPC_URL} --broadcast --private-key ${DEPLOYER_KEY} 2>&1`,
      { encoding: 'utf-8' }
    );

    // Parse treasury address
    const treasuryMatch = output.match(/AutocratTreasury:\s+(0x[a-fA-F0-9]+)/);
    if (treasuryMatch) {
      console.log(`   ✓ AutocratTreasury: ${treasuryMatch[1]}`);
      process.env.AUTOCRAT_TREASURY_1337 = treasuryMatch[1];
    } else {
      console.log('   Output:', output);
      throw new Error('Could not parse treasury address');
    }
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : String(error);
    console.error('   ✗ Deployment failed:', message);
    process.exit(1);
  }

  // 2. Fund bot wallet
  console.log('\n💰 Funding bot wallet...');

  const botBalance = await publicClient.getBalance({ address: botAccount.address });
  console.log(`   Current balance: ${formatEther(botBalance)} ETH`);

  if (botBalance < parseEther('10')) {
    const fundAmount = parseEther('100');
    const hash = await walletClient.sendTransaction({
      to: botAccount.address,
      value: fundAmount,
    });
    await publicClient.waitForTransactionReceipt({ hash });
    console.log(`   ✓ Sent ${formatEther(fundAmount)} ETH to bot`);

    const newBalance = await publicClient.getBalance({ address: botAccount.address });
    console.log(`   New balance: ${formatEther(newBalance)} ETH`);
  } else {
    console.log('   ✓ Bot has sufficient funds');
  }

  // 3. Generate env file
  console.log('\n📝 Writing .env file...');
  
  const envContent = `# Autocrat Localnet Configuration (generated by bootstrap.ts)
NETWORK=localnet
LOCALNET_RPC_URL=${RPC_URL}
AUTOCRAT_PRIVATE_KEY=${BOT_KEY}
AUTOCRAT_TREASURY_1337=${process.env.AUTOCRAT_TREASURY_1337}
AUTOCRAT_PRIMARY_CHAIN=1337
AUTOCRAT_ENABLED_CHAINS=1337
AUTOCRAT_LOG_LEVEL=info
`;

  const envPath = join(__dirname, '../.env');
  await Bun.write(envPath, envContent);
  console.log(`   ✓ Written to ${envPath}`);

  // 4. Start autocrat
  console.log('\n🤖 Starting Autocrat...');
  console.log('   Run: bun run dev\n');

  console.log('╔════════════════════════════════════════╗');
  console.log('║     BOOTSTRAP COMPLETE                 ║');
  console.log('╚════════════════════════════════════════╝\n');
}

main().catch((error) => {
  console.error('Bootstrap failed:', error);
  process.exit(1);
});
