# Bundler values for localnet (disabled)

replicaCount: 0

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

config:
  network: "localnet"
  rpcUrl: "http://reth-rpc:8545"
  debugMode: true



