# Bundler values for mainnet

replicaCount: 3

resources:
  limits:
    cpu: 2000m
    memory: 4Gi
  requests:
    cpu: 1000m
    memory: 2Gi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

nodeSelector:
  role: core

tolerations:
  - key: workload
    operator: Equal
    value: core
    effect: NoSchedule

config:
  network: "mainnet"
  rpcUrl: "http://reth-rpc:8545"
  debugMode: false

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - bundler
        topologyKey: kubernetes.io/hostname



