replicaCount: 2

image:
  repository: ghcr.io/stackup-wallet/stackup-bundler
  pullPolicy: IfNotPresent
  tag: "v0.6.0"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "4337"

podSecurityContext:
  fsGroup: 1000
  runAsUser: 1000
  runAsNonRoot: true

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 4337
  metricsPort: 8080

resources:
  limits:
    cpu: 2000m
    memory: 4Gi
  requests:
    cpu: 1000m
    memory: 2Gi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - bundler
        topologyKey: kubernetes.io/hostname

config:
  network: "jeju"
  rpcUrl: "http://reth-rpc:8545"
  entryPoint: "0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789"
  bundlerPrivateKey: ""  # Should be injected from Vault
  beneficiary: ""  # Address to receive bundler fees
  minBalance: "0.1"  # Minimum balance in ETH
  maxBatchSize: 10
  maxOpsPerBatch: 10
  port: 4337
  metricsPort: 8080
  debugMode: false
  userOpMempool: "p2p"  # or "local"
  p2p:
    enabled: true
    port: 4337
    bootnodes: []
  rateLimit:
    enabled: true
    rps: 100
    burst: 200


