apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "op-proposer.fullname" . }}
  labels:
    {{- include "op-proposer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "op-proposer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      labels:
        {{- include "op-proposer.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "op-proposer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - op-proposer
        args:
        - --l1-eth-rpc={{ .Values.config.l1.rpcUrl }}
        - --rollup-rpc={{ .Values.config.rollup.rpcUrl }}
        - --l2oo-address={{ .Values.config.l2oo.address }}
        - --poll-interval={{ .Values.config.pollInterval }}
        - --num-confirmations={{ .Values.config.numConfirmations }}
        - --network-timeout={{ .Values.config.networkTimeout }}
        {{- if .Values.config.privateKey }}
        - --private-key={{ .Values.config.privateKey }}
        {{- else }}
        - --private-key=/secrets/private-key
        {{- end }}
        {{- if .Values.config.metrics.enabled }}
        - --metrics.enabled
        - --metrics.addr={{ .Values.config.metrics.addr }}
        - --metrics.port={{ .Values.config.metrics.port }}
        {{- end }}
        {{- if .Values.config.pprof.enabled }}
        - --pprof.enabled
        - --pprof.addr=0.0.0.0
        - --pprof.port=6060
        {{- end }}
        ports:
        - name: metrics
          containerPort: {{ .Values.config.metrics.port }}
          protocol: TCP
        {{- if .Values.config.pprof.enabled }}
        - name: pprof
          containerPort: 6060
          protocol: TCP
        {{- end }}
        livenessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - name: secrets
          mountPath: /secrets
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: {{ include "op-proposer.fullname" . }}-secrets
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

