# EigenDA values for mainnet

replicaCount: 2

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

nodeSelector:
  role: core

tolerations:
  - key: workload
    operator: Equal
    value: core
    effect: NoSchedule

config:
  disperserRpc: "disperser.eigenda.xyz:443"
  retrieverRpc: "retriever.eigenda.xyz:443"
  attestationServiceUrl: "https://attestation.eigenda.xyz"

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - eigenda
        topologyKey: kubernetes.io/hostname



