replicaCount: 2

image:
  repository: ghcr.io/layr-labs/eigenda/opr-proxy
  pullPolicy: IfNotPresent
  tag: "v0.6.0"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "9100"

podSecurityContext:
  fsGroup: 1000
  runAsUser: 1000
  runAsNonRoot: true

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 4242
  metricsPort: 9100

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

nodeSelector:
  role: core

tolerations:
  - key: workload
    operator: Equal
    value: core
    effect: NoSchedule

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - eigenda
        topologyKey: kubernetes.io/hostname

config:
  disperserRpc: "disperser-holesky.eigenda.xyz:443"
  retrieverRpc: "retriever-holesky.eigenda.xyz:443"
  attestationServiceUrl: "https://attestation-holesky.eigenda.xyz"
  listenAddr: "0.0.0.0:4242"
  metricsAddr: "0.0.0.0:9100"
  minConfirmations: 6
  timeout: "30s"
  batchSize: 10
  # For mainnet, update endpoints:
  # disperserRpc: "disperser.eigenda.xyz:443"
  # retrieverRpc: "retriever.eigenda.xyz:443"
  # attestationServiceUrl: "https://attestation.eigenda.xyz"


