# EigenDA values for localnet (disabled for simplicity)

replicaCount: 0

resources:
  limits:
    cpu: 250m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

nodeSelector: {}

tolerations: []

config:
  disperserRpc: "disperser-holesky.eigenda.xyz:443"
  retrieverRpc: "retriever-holesky.eigenda.xyz:443"
  attestationServiceUrl: "https://attestation-holesky.eigenda.xyz"



