# EigenDA values for testnet

replicaCount: 1

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

nodeSelector:
  role: core

tolerations:
  - key: workload
    operator: Equal
    value: core
    effect: NoSchedule

config:
  disperserRpc: "disperser-holesky.eigenda.xyz:443"
  retrieverRpc: "retriever-holesky.eigenda.xyz:443"
  attestationServiceUrl: "https://attestation-holesky.eigenda.xyz"



