# Subsquid values for mainnet

processor:
  image:
    repository: ghcr.io/jeju-l3/subsquid-processor
    tag: "latest"  # Update with specific version tag when deploying

  replicaCount: 1  # Single processor for consistency

  resources:
    requests:
      memory: "2Gi"
      cpu: "1000m"
    limits:
      memory: "4Gi"
      cpu: "2000m"

  env:
    - name: RPC_ENDPOINT
      value: "http://reth-rpc.rpc:8545"
    - name: START_BLOCK
      value: "0"
    - name: CHAIN_ID
      value: "420691"
    - name: DB_HOST
      value: "subsquid-postgres"
    - name: DB_PORT
      value: "5432"
    - name: DB_NAME
      value: "indexer"
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: subsquid-db-secret
          key: username
    - name: DB_PASS
      valueFrom:
        secretKeyRef:
          name: subsquid-db-secret
          key: password

api:
  replicaCount: 3

  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"

  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80

postgres:
  enabled: true

  resources:
    requests:
      memory: "4Gi"
      cpu: "2000m"
    limits:
      memory: "8Gi"
      cpu: "4000m"

  persistence:
    enabled: true
    size: "500Gi"
    storageClass: "gp3"

ingress:
  enabled: true
  hosts:
    - host: indexer.jeju.network
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: subsquid-mainnet-tls
      hosts:
        - indexer.jeju.network


