apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "op-batcher.fullname" . }}
  labels:
    {{- include "op-batcher.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "op-batcher.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      labels:
        {{- include "op-batcher.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "op-batcher.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - op-batcher
        args:
        - --l1-eth-rpc={{ .Values.config.l1.rpcUrl }}
        - --l2-eth-rpc={{ .Values.config.l2.rpcUrl }}
        - --rollup-rpc={{ .Values.config.rollup.rpcUrl }}
        - --max-channel-duration={{ .Values.config.maxChannelDuration }}
        - --sub-safety-margin={{ .Values.config.subSafetyMargin }}
        - --poll-interval={{ .Values.config.pollInterval }}
        - --num-confirmations={{ .Values.config.numConfirmations }}
        - --safe-abort-nonce-too-low-count={{ .Values.config.safeAbortNonceTooLowCount }}
        - --resubmission={{ .Values.config.resubmission }}
        - --batch-type={{ .Values.config.batchType }}
        {{- if eq .Values.config.dataAvailability.type "eigenda" }}
        - --data-availability-type=eigenda
        - --eigenda-proxy-url=http://eigenda:4242
        {{- else if eq .Values.config.dataAvailability.type "blobs" }}
        - --data-availability-type=blobs
        {{- else }}
        - --data-availability-type=calldata
        {{- end }}
        {{- if .Values.config.privateKey }}
        - --private-key={{ .Values.config.privateKey }}
        {{- else }}
        - --private-key=/secrets/private-key
        {{- end }}
        {{- if .Values.config.sequencerHd }}
        - --sequencer-hd={{ .Values.config.sequencerHd }}
        {{- end }}
        {{- if .Values.config.metrics.enabled }}
        - --metrics.enabled
        - --metrics.addr={{ .Values.config.metrics.addr }}
        - --metrics.port={{ .Values.config.metrics.port }}
        {{- end }}
        {{- if .Values.config.pprof.enabled }}
        - --pprof.enabled
        - --pprof.addr=0.0.0.0
        - --pprof.port=6060
        {{- end }}
        ports:
        - name: metrics
          containerPort: {{ .Values.config.metrics.port }}
          protocol: TCP
        {{- if .Values.config.pprof.enabled }}
        - name: pprof
          containerPort: 6060
          protocol: TCP
        {{- end }}
        livenessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - name: secrets
          mountPath: /secrets
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: {{ include "op-batcher.fullname" . }}-secrets
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

