apiVersion: v1
kind: Secret
metadata:
  name: {{ include "op-batcher.fullname" . }}-secrets
  labels:
    {{- include "op-batcher.labels" . | nindent 4 }}
  annotations:
    # This secret should be managed by External Secrets Operator or Vault in production
    # The private key below is a placeholder - replace with Vault integration
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "op-batcher"
    vault.hashicorp.com/agent-inject-secret-private-key: "secret/data/jeju/{{ .Release.Namespace }}/op-batcher"
    vault.hashicorp.com/agent-inject-template-private-key: |
      {{`{{- with secret "secret/data/jeju/`}}{{ .Release.Namespace }}{{`/op-batcher" -}}
      {{ .Data.data.privateKey }}
      {{- end }}`}}
type: Opaque
data:
  # WARNING: This is a placeholder. In production, use Vault or External Secrets Operator
  # The private key should never be committed to git
  private-key: {{ .Values.config.privateKey | default "" | b64enc | quote }}

