apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bundler.fullname" . }}-config
  labels:
    {{- include "bundler.labels" . | nindent 4 }}
data:
  config.yaml: |
    network: {{ .Values.config.network }}
    rpcUrl: {{ .Values.config.rpcUrl }}
    entryPoint: {{ .Values.config.entryPoint }}
    beneficiary: {{ .Values.config.beneficiary }}
    minBalance: {{ .Values.config.minBalance }}
    maxBatchSize: {{ .Values.config.maxBatchSize }}
    maxOpsPerBatch: {{ .Values.config.maxOpsPerBatch }}
    port: {{ .Values.config.port }}
    metricsPort: {{ .Values.config.metricsPort }}
    debugMode: {{ .Values.config.debugMode }}
    userOpMempool: {{ .Values.config.userOpMempool }}
    {{- if .Values.config.rateLimit.enabled }}
    rateLimit:
      enabled: true
      rps: {{ .Values.config.rateLimit.rps }}
      burst: {{ .Values.config.rateLimit.burst }}
    {{- end }}

