apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bundler.fullname" . }}-secrets
  labels:
    {{- include "bundler.labels" . | nindent 4 }}
  annotations:
    # This secret should be managed by External Secrets Operator or Vault in production
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "bundler"
    vault.hashicorp.com/agent-inject-secret-private-key: "secret/data/jeju/{{ .Release.Namespace }}/bundler"
    vault.hashicorp.com/agent-inject-template-private-key: |
      {{`{{- with secret "secret/data/jeju/`}}{{ .Release.Namespace }}{{`/bundler" -}}
      {{ .Data.data.privateKey }}
      {{- end }}`}}
type: Opaque
data:
  # WARNING: This is a placeholder. In production, use Vault or External Secrets Operator
  private-key: {{ .Values.config.bundlerPrivateKey | default "" | b64enc | quote }}

