apiVersion: v1
kind: Service
metadata:
  name: {{ include "bundler.fullname" . }}
  labels:
    {{- include "bundler.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: rpc
    protocol: TCP
    name: rpc
  - port: {{ .Values.service.metricsPort }}
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    {{- include "bundler.selectorLabels" . | nindent 4 }}

