# Reth Archive values for testnet - single node
replicaCount: 1

resources:
  limits:
    cpu: 4000m
    memory: 16Gi
  requests:
    cpu: 2000m
    memory: 8Gi

persistence:
  enabled: true
  storageClass: gp3
  size: 2Ti

autoscaling:
  enabled: false

nodeSelector:
  role: data

tolerations:
  - key: workload
    operator: Equal
    value: data
    effect: NoSchedule

service:
  type: ClusterIP


