# Reth RPC values for mainnet - auto-scaling pool
replicaCount: 5

resources:
  limits:
    cpu: 4000m
    memory: 8Gi
  requests:
    cpu: 2000m
    memory: 4Gi

persistence:
  enabled: true
  storageClass: gp3
  size: 500Gi

autoscaling:
  enabled: true
  minReplicas: 5
  maxReplicas: 15
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

nodeSelector:
  role: rpc

tolerations:
  - key: workload
    operator: Equal
    value: rpc
    effect: NoSchedule

service:
  type: ClusterIP

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - reth
          - key: mode
            operator: In
            values:
            - rpc
        topologyKey: kubernetes.io/hostname


