# Reth Archive values for mainnet - auto-scaling pool
replicaCount: 2

resources:
  limits:
    cpu: 8000m
    memory: 32Gi
  requests:
    cpu: 4000m
    memory: 16Gi

persistence:
  enabled: true
  storageClass: gp3
  size: 2Ti

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

nodeSelector:
  role: data

tolerations:
  - key: workload
    operator: Equal
    value: data
    effect: NoSchedule

service:
  type: ClusterIP

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - reth
          - key: mode
            operator: In
            values:
            - archive
        topologyKey: kubernetes.io/hostname


