# Reth Archive values for localnet - disabled for cost
replicaCount: 0

resources:
  limits:
    cpu: 1000m
    memory: 4Gi
  requests:
    cpu: 500m
    memory: 2Gi

persistence:
  enabled: false

autoscaling:
  enabled: false


