# Reth RPC values for localnet
replicaCount: 1

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

persistence:
  enabled: false

autoscaling:
  enabled: false

nodeSelector: {}
tolerations: []


