{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "rpc-gateway.fullname" . }}
  labels:
    {{- include "rpc-gateway.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    {{- $host := .host }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "rpc-gateway.fullname" $ }}
                port:
                  {{- if or (eq $host "ws.jeju.network") (eq $host "testnet-ws.jeju.network") }}
                  number: {{ $.Values.service.ws.port }}
                  {{- else }}
                  number: {{ $.Values.service.http.port }}
                  {{- end }}
          {{- end }}
    {{- end }}
{{- end }}

