apiVersion: v1
kind: Service
metadata:
  name: {{ include "reth.fullname" . }}
  labels:
    {{- include "reth.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.http.port }}
    targetPort: http
    protocol: TCP
    name: http
  - port: {{ .Values.service.ws.port }}
    targetPort: ws
    protocol: TCP
    name: ws
  - port: {{ .Values.service.engine.port }}
    targetPort: engine
    protocol: TCP
    name: engine
  - port: {{ .Values.service.p2p.port }}
    targetPort: p2p
    protocol: TCP
    name: p2p
  - port: {{ .Values.service.metrics.port }}
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    {{- include "reth.selectorLabels" . | nindent 4 }}
    mode: {{ .Values.mode }}


