// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "forge-std/Script.sol";
import { IWorld } from "../src/hyperscape/src/codegen/world/IWorld.sol";

/**
 * @title DeployHyperscape
 * @notice Foundry script to deploy Hyperscape MUD world
 * @dev Run with: forge script script/DeployHyperscape.s.sol --rpc-url $RPC_URL --broadcast
 */
contract DeployHyperscape is Script {
    function run() external {
        uint256 deployerPrivateKey = vm.envUint("PRIVATE_KEY");
        address deployer = vm.addr(deployerPrivateKey);
        
        console.log("================================================");
        console.log("Deploying Hyperscape MUD World");
        console.log("================================================");
        console.log("Deployer:", deployer);
        console.log("Chain ID:", block.chainid);
        console.log("");
        
        vm.startBroadcast(deployerPrivateKey);
        
        // Deploy MUD World (this will be generated by MUD CLI)
        // For now, we document the expected flow:
        
        console.log("1. Deploying World contract...");
        // World deployment handled by MUD CLI: `mud deploy`
        
        console.log("2. Deploying Systems...");
        // Systems:
        // - PlayerSystem
        // - CombatSystem
        // - InventorySystem
        // - EquipmentSystem
        // - SkillSystem
        // - ResourceSystem
        // - MobSystem
        // - AdminSystem
        
        console.log("3. Registering Systems with World...");
        // MUD CLI handles registration
        
        console.log("4. Initializing World...");
        // Call AdminSystem.initialize() to set up items and loot tables
        // IWorld world = IWorld(worldAddress);
        // world.hyperscape__initialize();
        
        console.log("5. Spawning Initial Mobs...");
        // Spawn starter mobs around the world
        // For each starter town, spawn 5-10 goblins nearby
        
        console.log("6. Spawning Resources...");
        // Spawn trees and fishing spots around the world
        
        vm.stopBroadcast();
        
        console.log("");
        console.log("================================================");
        console.log("Hyperscape Deployment Complete!");
        console.log("================================================");
        console.log("");
        console.log("Next steps:");
        console.log("1. Run MUD indexer to index game state");
        console.log("2. Start Hyperscape client");
        console.log("3. Connect wallet and play!");
        console.log("");
    }
}

