name: Verify Deployment

on:
  schedule:
    # Check every 6 hours that the site is up
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  verify-site:
    runs-on: ubuntu-latest
    steps:
      - name: Check Lander Site
        run: |
          echo "Checking if lander site is accessible..."
          # Extract repository name from full repository path
          REPO_FULL="${{ github.repository }}"
          REPO_OWNER="${{ github.repository_owner }}"
          REPO_NAME="${REPO_FULL#*/}"  # Remove owner prefix
          response=$(curl -s -o /dev/null -w "%{http_code}" "https://${REPO_OWNER}.github.io/${REPO_NAME}/")

          if [ "$response" = "200" ]; then
            echo "✅ Lander site is accessible at https://${REPO_OWNER}.github.io/${REPO_NAME}/"
          else
            echo "❌ Lander site returned HTTP $response"
            exit 1
          fi

      - name: Check GitHub API Access
        run: |
          echo "Verifying GitHub API access for releases..."
          response=$(curl -s -o /dev/null -w "%{http_code}" https://api.github.com/repos/${{ github.repository }}/releases)

          if [ "$response" = "200" ]; then
            echo "✅ GitHub API is accessible"
          else
            echo "❌ GitHub API returned HTTP $response"
            exit 1
          fi

      - name: Notify on Failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🚨 Deployment Verification Failed',
              body: `The deployment verification failed at ${new Date().toISOString()}.
              
              Please check:
              - GitHub Pages deployment status
              - DNS/CDN issues
              - GitHub API rate limits
              
              Workflow: ${context.workflow}
              Run: ${context.runNumber}`,
              labels: ['deployment', 'bug']
            });
