replicaCount: 1

image:
  repository: metabase/metabase
  pullPolicy: IfNotPresent
  tag: "v0.48.0"

service:
  type: LoadBalancer
  port: 3000
  targetPort: 3000

resources:
  requests:
    memory: "1Gi"
    cpu: "500m"
  limits:
    memory: "2Gi"
    cpu: "1000m"

env:
  - name: MB_DB_TYPE
    value: "postgres"
  - name: MB_DB_DBNAME
    value: "metabase"
  - name: MB_DB_PORT
    value: "5432"
  - name: MB_DB_USER
    valueFrom:
      secretKeyRef:
        name: metabase-db-secret
        key: username
  - name: MB_DB_PASS
    valueFrom:
      secretKeyRef:
        name: metabase-db-secret
        key: password
  - name: MB_DB_HOST
    value: "metabase-postgres"
  - name: MB_EMOJI_IN_LOGS
    value: "true"
  - name: JAVA_OPTS
    value: "-Xmx1g"

postgres:
  enabled: true
  image:
    repository: postgres
    tag: "15-alpine"
  
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  
  persistence:
    enabled: true
    size: "10Gi"
    storageClass: "gp3"

persistence:
  enabled: false

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: analytics.jeju.network
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: metabase-tls
      hosts:
        - analytics.jeju.network

serviceAccount:
  create: true
  annotations: {}
  name: "metabase"

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 2000
  fsGroup: 2000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false

