apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "op-node.fullname" . }}
  labels:
    {{- include "op-node.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "op-node.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      labels:
        {{- include "op-node.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "op-node.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      - name: init-data-dir
        image: busybox:1.36
        command: ['sh', '-c', 'mkdir -p /data && chown -R 1000:1000 /data']
        volumeMounts:
        - name: data
          mountPath: /data
        securityContext:
          runAsUser: 0
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - op-node
        args:
        - --network={{ .Values.config.network }}
        - --l1={{ .Values.config.l1.rpcUrl }}
        - --l1.rpckind={{ .Values.config.l1.rpcKind }}
        - --l2={{ .Values.config.l2.engineRpc }}
        - --l2.jwt-secret={{ .Values.config.l2.engineJwtSecret }}
        - --rpc.addr={{ .Values.config.rpc.addr }}
        - --rpc.port={{ .Values.config.rpc.port }}
        {{- if .Values.config.rpc.enableAdmin }}
        - --rpc.enable-admin
        {{- end }}
        - --p2p.listen.ip={{ .Values.config.p2p.listen.ip }}
        - --p2p.listen.tcp={{ .Values.config.p2p.listen.tcp }}
        - --p2p.listen.udp={{ .Values.config.p2p.listen.udp }}
        {{- if .Values.config.p2p.advertiseIp }}
        - --p2p.advertise.ip={{ .Values.config.p2p.advertiseIp }}
        {{- end }}
        - --p2p.peers.lo={{ .Values.config.p2p.peersLo }}
        - --p2p.peers.hi={{ .Values.config.p2p.peersHi }}
        {{- range .Values.config.p2p.bootnodes }}
        - --p2p.bootnodes={{ . }}
        {{- end }}
        {{- range .Values.config.p2p.static }}
        - --p2p.static={{ . }}
        {{- end }}
        - --metrics.enabled={{ .Values.config.metrics.enabled }}
        - --metrics.addr={{ .Values.config.metrics.addr }}
        - --metrics.port={{ .Values.config.metrics.port }}
        - --snapshotlog.file={{ .Values.config.snapshotLog }}
        {{- if .Values.config.conductor.enabled }}
        - --conductor.enabled
        - --conductor.rpc={{ .Values.config.conductor.rpc }}
        {{- end }}
        - --rollup.config={{ .Values.config.rollup }}
        ports:
        - name: rpc
          containerPort: {{ .Values.config.rpc.port }}
          protocol: TCP
        - name: p2p-tcp
          containerPort: {{ .Values.config.p2p.listen.tcp }}
          protocol: TCP
        - name: p2p-udp
          containerPort: {{ .Values.config.p2p.listen.udp }}
          protocol: UDP
        - name: metrics
          containerPort: {{ .Values.config.metrics.port }}
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: rpc
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: rpc
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - name: data
          mountPath: {{ .Values.persistence.mountPath }}
        - name: config
          mountPath: /config
          readOnly: true
        - name: secrets
          mountPath: /secrets
          readOnly: true
      volumes:
      - name: data
        {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ include "op-node.fullname" . }}
        {{- else }}
        emptyDir: {}
        {{- end }}
      - name: config
        configMap:
          name: {{ include "op-node.fullname" . }}-config
      - name: secrets
        secret:
          secretName: {{ include "op-node.fullname" . }}-secrets
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}


