apiVersion: v1
kind: Secret
metadata:
  name: {{ include "op-node.fullname" . }}-secrets
  labels:
    {{- include "op-node.labels" . | nindent 4 }}
type: Opaque
data:
  # JWT secret should be injected from external secret manager (e.g., Vault)
  # For now, this is a placeholder that should be replaced
  jwt-secret.txt: {{ randAlphaNum 32 | b64enc | quote }}



