apiVersion: v1
kind: Service
metadata:
  name: {{ include "op-node.fullname" . }}
  labels:
    {{- include "op-node.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.rpc.port }}
    targetPort: rpc
    protocol: TCP
    name: rpc
  - port: {{ .Values.service.p2p.port }}
    targetPort: p2p-tcp
    protocol: TCP
    name: p2p-tcp
  - port: {{ .Values.service.p2p.port }}
    targetPort: p2p-udp
    protocol: UDP
    name: p2p-udp
  - port: {{ .Values.service.metrics.port }}
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    {{- include "op-node.selectorLabels" . | nindent 4 }}


