[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 999999
via_ir = true
evm_version = "cancun"

# Test settings
verbosity = 2
fuzz_runs = 256

# Remappings
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@optimism/=lib/optimism/packages/contracts-bedrock/src/",
    "forge-std/=lib/forge-std/src/",
    "@eth-optimism-bedrock/=lib/optimism/packages/contracts-bedrock/src/",
    "account-abstraction/=lib/account-abstraction/contracts/"
]

# RPC endpoints (override with env vars)
[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
base = "${BASE_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
local = "http://127.0.0.1:8545"

# Etherscan API keys
[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }
base_sepolia = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }


