[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
auto_detect_solc = true
optimizer = true
optimizer_runs = 999999
via_ir = true
evm_version = "cancun"

# Exclude incomplete contracts and problematic dependencies
deny_warnings = false
exclude = [
    "lib/account-abstraction/**",
    "lib/openzeppelin-contracts/test/**",
    "lib/openzeppelin-contracts/lib/**",
    "lib/openzeppelin-contracts-upgradeable/test/**",
    "lib/openzeppelin-contracts-upgradeable/lib/**",
    "src/paymaster/CloudPaymaster.sol",
    "src/prediction/JejuMarket.sol",
    "src/uniswap-v4/**",
    "src/hyperscape/src/test/**",
    "src/hyperscape/src/systems/**",
    "src/hyperscape/src/codegen/**"
]

# Test settings
verbosity = 2
fuzz_runs = 256
fs_permissions = [{ access = "read-write", path = "./deployments" }, { access = "read", path = "./" }]

# Remappings
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@optimism/=lib/optimism/packages/contracts-bedrock/src/",
    "forge-std/=lib/forge-std/src/",
    "@eth-optimism-bedrock/=lib/optimism/packages/contracts-bedrock/src/",
    "account-abstraction/=lib/account-abstraction/contracts/",
    "@latticexyz/store/=src/hyperscape/node_modules/@latticexyz/store/",
    "@latticexyz/world/=src/hyperscape/node_modules/@latticexyz/world/",
    "@latticexyz/schema-type/=src/hyperscape/node_modules/@latticexyz/schema-type/",
    "@latticexyz/config/=src/hyperscape/node_modules/@latticexyz/config/",
]

# RPC endpoints (override with env vars)
[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
base = "${BASE_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
local = "http://127.0.0.1:8545"

# Etherscan API keys
[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }
base_sepolia = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }


