name: elizaos
base: core22
version: '2.0.0'
summary: ELIZA - Autonomous AI agent life simulation game
description: |
  ELIZA is an AI sandbox life simulation game where you foster a nascent 
  AI agent from a blank slate to a self-actualized digital being. Unlike 
  traditional simulations, ELIZA's AI is not scripted – it leverages a 
  real autonomous agent running on ElizaOS to drive emergent behavior.

  The agent starts with no built-in knowledge, personality, or purpose, 
  and must learn about the world, form relationships, and define its 
  goals in real-time through interaction.

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  elizaos:
    command: elizaos
    extensions: [gnome]
    plugs:
      - network
      - network-bind
      - home
      - removable-media
      - audio-playback
      - opengl
      - x11
      - wayland
      - desktop
      - desktop-legacy
      - gsettings
      - unity7
    environment:
      WEBKIT_DISABLE_COMPOSITING_MODE: 1
      GDK_BACKEND: x11,wayland

parts:
  elizaos:
    plugin: nil
    source: .
    build-packages:
      - curl
      - wget
      - build-essential
      - libssl-dev
      - libgtk-3-dev
      - libwebkit2gtk-4.0-dev
      - libayatana-appindicator3-dev
      - librsvg2-dev
      - libglib2.0-dev
      - libjavascriptcoregtk-4.0-dev
      - libsoup2.4-dev
      - nodejs
      - npm
    stage-packages:
      - libwebkit2gtk-4.0-37
      - libgtk-3-0
      - libayatana-appindicator3-1
      - libssl3
      - libglib2.0-0
      - libjavascriptcoregtk-4.0-18
      - libsoup2.4-1
    override-build: |
      # Install Rust
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      export PATH="$HOME/.cargo/bin:$PATH"

      # Build the application
      cd packages/game
      npm install
      npm run build

      # Copy the built binary
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp src-tauri/target/release/elizaos $SNAPCRAFT_PART_INSTALL/bin/

      # Copy resources
      mkdir -p $SNAPCRAFT_PART_INSTALL/share/elizaos
      cp -r dist/* $SNAPCRAFT_PART_INSTALL/share/elizaos/

      # Create desktop file
      mkdir -p $SNAPCRAFT_PART_INSTALL/share/applications
      cat > $SNAPCRAFT_PART_INSTALL/share/applications/elizaos.desktop << EOF
      [Desktop Entry]
      Name=ELIZA
      Comment=Autonomous AI agent life simulation game
      Exec=elizaos
      Icon=elizaos
      Terminal=false
      Type=Application
      Categories=Game;Simulation;
      StartupNotify=true
      EOF

      # Copy icon
      mkdir -p $SNAPCRAFT_PART_INSTALL/share/icons/hicolor/512x512/apps
      cp src-tauri/icons/icon.png $SNAPCRAFT_PART_INSTALL/share/icons/hicolor/512x512/apps/elizaos.png

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0
