[test]
# Global test timeout in milliseconds
# Use shorter timeout in CI to prevent hanging
timeout = 60000

# Coverage configuration
coverage = true

[install]
# Optimize installation for CI
cache = true
auto = "fallback"

# Trusted dependencies that require postinstall scripts or native bindings
trustedDependencies = [
  "@tensorflow/tfjs-node",
  "@tensorflow-models/coco-ssd",
  "@tensorflow-models/pose-detection",
  "@tensorflow-models/posenet",
  "@tensorflow-models/mobilenet",
  "canvas",
  "sharp"
]

[run]
# Bun runtime optimizations
shell = "system"

coverage-exclude = [
  "**/dist/**",
  "**/build/**",
  "**/chunk-*.js",
  "**/*.chunk.js",
  "**/node_modules/**",
  "**/*.min.js",
  "**/*.bundle.js",
  "**/coverage/**",
  "**/.turbo/**",
]