#!/bin/bash
#
# Jeju AI Council - Development Start Script
#
# This script starts the full development environment:
# 1. Anvil (local blockchain)
# 2. Deploy contracts
# 3. Council API
# 4. Ollama (if not running)
# 5. Council Frontend
#
# Usage:
#   ./scripts/start-council-dev.sh          # Start everything
#   ./scripts/start-council-dev.sh --no-ui  # Start without frontend
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log() { echo -e "${BLUE}[$(date +%H:%M:%S)]${NC} $1"; }
success() { echo -e "${GREEN}✓${NC} $1"; }
warn() { echo -e "${YELLOW}⚠${NC} $1"; }
fail() { echo -e "${RED}✗${NC} $1"; }

# Parse arguments
NO_UI=false
for arg in "$@"; do
  case $arg in
    --no-ui) NO_UI=true ;;
  esac
done

log "Starting Jeju AI Council development environment"
echo ""

# Check dependencies
command -v bun >/dev/null 2>&1 || { fail "bun is required. Install: https://bun.sh"; exit 1; }
command -v anvil >/dev/null 2>&1 || { fail "anvil is required. Install: foundryup"; exit 1; }
command -v forge >/dev/null 2>&1 || { fail "forge is required. Install: foundryup"; exit 1; }

# Kill existing processes
log "Cleaning up existing processes..."
pkill -f "anvil --port 9545" 2>/dev/null || true
pkill -f "bun.*council/src/index" 2>/dev/null || true
pkill -f "next dev.*council/app" 2>/dev/null || true
sleep 2

# 1. Start Anvil
log "Starting anvil..."
anvil --port 9545 > /tmp/anvil.log 2>&1 &
ANVIL_PID=$!
sleep 3

# Check anvil is running
if ! curl -s http://localhost:9545 -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' > /dev/null 2>&1; then
  fail "Failed to start anvil"
  exit 1
fi
success "Anvil running (PID: $ANVIL_PID)"

# 2. Deploy contracts
log "Deploying contracts..."
cd "$PROJECT_ROOT/packages/contracts"
BASESCAN_API_KEY=dummy ETHERSCAN_API_KEY=dummy forge script script/DeployDAO.s.sol --rpc-url http://localhost:9545 --broadcast 2>&1 | tee /tmp/deploy.log

# Extract addresses from deployment output
COUNCIL=$(grep "Council:" /tmp/deploy.log | tail -1 | awk '{print $2}')
CEO=$(grep "CEOAgent:" /tmp/deploy.log | tail -1 | awk '{print $2}')
TOKEN=$(grep "GovernanceToken:" /tmp/deploy.log | tail -1 | awk '{print $2}')
IDENTITY=$(grep "IdentityRegistry:" /tmp/deploy.log | tail -1 | awk '{print $2}')
REPUTATION=$(grep "ReputationRegistry:" /tmp/deploy.log | tail -1 | awk '{print $2}')
QUALITY=$(grep "QualityOracle:" /tmp/deploy.log | tail -1 | awk '{print $2}')

if [ -z "$COUNCIL" ]; then
  fail "Failed to deploy contracts"
  exit 1
fi
success "Contracts deployed"

# 3. Generate .env file
log "Generating configuration..."
cat > "$PROJECT_ROOT/apps/council/.env" << EOF
# Auto-generated by start-council-dev.sh
RPC_URL=http://127.0.0.1:9545
CHAIN_ID=31337
COUNCIL_ADDRESS=$COUNCIL
CEO_AGENT_ADDRESS=$CEO
GOVERNANCE_TOKEN_ADDRESS=$TOKEN
IDENTITY_REGISTRY_ADDRESS=$IDENTITY
REPUTATION_REGISTRY_ADDRESS=$REPUTATION
QUALITY_ORACLE_ADDRESS=$QUALITY
OPERATOR_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
ASSESSOR_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
OLLAMA_URL=http://localhost:11434
OLLAMA_MODEL=llama3.2:3b
EOF
success "Configuration generated"

# 4. Check Ollama
if curl -s http://localhost:11434/api/tags > /dev/null 2>&1; then
  success "Ollama already running"
else
  warn "Ollama not running. Start it separately for AI features: ollama serve"
fi

# 5. Start Council API
log "Starting Council API..."
cd "$PROJECT_ROOT/apps/council"
PORT=8010 bun run src/index.ts > /tmp/council-api.log 2>&1 &
API_PID=$!
sleep 5

if curl -s http://localhost:8010/health > /dev/null 2>&1; then
  success "Council API running (PID: $API_PID)"
else
  fail "Failed to start Council API"
  cat /tmp/council-api.log
  exit 1
fi

# 6. Start Frontend (optional)
if [ "$NO_UI" = false ]; then
  log "Starting Council Frontend..."
  cd "$PROJECT_ROOT/apps/council/app"
  bun run dev > /tmp/council-frontend.log 2>&1 &
  FRONTEND_PID=$!
  sleep 5
  success "Council Frontend running (PID: $FRONTEND_PID)"
fi

# Summary
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "  JEJU AI COUNCIL - DEVELOPMENT ENVIRONMENT READY"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "  Services:"
echo "    Anvil:    http://localhost:9545"
echo "    API:      http://localhost:8010"
if [ "$NO_UI" = false ]; then
echo "    Frontend: http://localhost:3000"
fi
echo ""
echo "  Contracts:"
echo "    Council:       $COUNCIL"
echo "    CEOAgent:      $CEO"
echo "    QualityOracle: $QUALITY"
echo ""
echo "  Logs:"
echo "    tail -f /tmp/anvil.log"
echo "    tail -f /tmp/council-api.log"
if [ "$NO_UI" = false ]; then
echo "    tail -f /tmp/council-frontend.log"
fi
echo ""
echo "  To stop: pkill -f anvil; pkill -f 'bun.*council'"
echo "═══════════════════════════════════════════════════════════════"
