[profile.default]
src = "src"
out = "out"
libs = ["../../lib", "node_modules"]
test = "src/test"
solc_version = "0.8.24"
auto_detect_solc = false
optimizer = true
optimizer_runs = 999999
via_ir = true
evm_version = "cancun"

# Test settings
verbosity = 2
fuzz_runs = 256

# Remappings for MUD
remappings = [
    "@latticexyz/store/=node_modules/@latticexyz/store/",
    "@latticexyz/world/=node_modules/@latticexyz/world/",
    "@latticexyz/schema-type/=node_modules/@latticexyz/schema-type/",
    "@latticexyz/config/=node_modules/@latticexyz/config/",
    "forge-std/=../../lib/forge-std/src/",
]

deny_warnings = false

