name: Documentation CI

on:
  push:
    branches: [main, develop]
    paths:
      - 'documentation/**'
      - '*.md'
  pull_request:
    branches: [main, develop]
    paths:
      - 'documentation/**'
      - '*.md'

jobs:
  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Lint markdown files
        uses: avto-dev/markdown-lint@v1
        with:
          args: '**/*.md'
          config: '.markdownlint.json'
        continue-on-error: true
      
      - name: Check for broken links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          config-file: '.markdown-link-check.json'
        continue-on-error: true

  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: bun install
      
      - name: Build documentation
        run: bun run docs:build
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-build
          path: documentation/.vitepress/dist

