# RPC Gateway values for localnet
replicaCount: 1

ingress:
  enabled: false  # No ingress for local

autoscaling:
  enabled: false

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

backend:
  rpcService: "reth-rpc"
  rpcPort: 8545
  wsPort: 8546

rateLimit:
  enabled: false  # No rate limiting for local

monitoring:
  enabled: false


